version: "3"
services:
    grpc:
      build: ./Server/Backend
      stdin_open: true
      tty: true
      ports: 
        - 5000:5000
    proxy:
      build: ./Envoy
      ports:
        - 8080:8080